### ISSUE TITLE
Requiring Module::Build::Tiny does not seem sensible.

### ISSUE THREAD

**Issue by kentfredric** [hideo55/Module-Build-XSUtil#9]
0.17 shipped with a stated purpose no other than to enable a 1 line fix for pure-perl support.

But as a side effect of its Minilla stack, it also replaced its entire install-time tooling.

And this means anyone using Module::Build::XSUtil not only needs Module::Build, but Module::Build::Tiny and all its deps as well.

And this just all seems very silly.

**Comment by kentfredric** [comment]
Ugh. This is extra fun, because one of your dependencies, Devel::CheckCompiler, *also* made the same change that snuck under the covers of some other [*trivial* change](https://metacpan.org/diff/file?source=SYOHEX/Devel-CheckCompiler-0.06&target=SYOHEX/Devel-CheckCompiler-0.07#Changes) back november last year -_-.  @syohex

**Comment by hideo55** [comment]
Thanks for reporting.
It fixed in f1be5d19590bb15002e9137914bfdcab6d982460, and I released Module-Build-XSUtil-0.18.
